### ISSUE TITLE
Incorrect ploted level order when using grouping

### ISSUE THREAD

**Issue by ruialv** [jbryer/likert#63]
Hello,

First things first: thank you for this great package! I use it a lot.
Now, let's try to replicate the bug(?).

`require(likert)`

Using demo data
`data(pisaitems)`
`items28 <- pisaitems[, substr(names(pisaitems), 1, 5) == "ST24Q"]`

Prepare data to plot likert
`l28 <- likert(items28)`

Levels are ploted in the correct order
`plot(l28)`

![image](https://cloud.githubusercontent.com/assets/14272525/20490899/7b9c78de-b007-11e6-9df6-0b785105d9b5.png)

Prepare grouped data by CNT to plot likert
`l28g <- likert(items28, grouping = pisaitems$CNT)`

"Strongly agree" apears before "Agree" level
`plot(l28g)`

![image](https://cloud.githubusercontent.com/assets/14272525/20490847/3a9021ba-b007-11e6-882b-25ad66866179.png)

Here's my session info:

> 

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
>
>locale:
[1] LC_COLLATE=Portuguese_Portugal.1252  LC_CTYPE=Portuguese_Portugal.1252   
[3] LC_MONETARY=Portuguese_Portugal.1252 LC_NUMERIC=C                        
[5] LC_TIME=Portuguese_Portugal.1252    
>
>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
[1] likert_1.3.4  xtable_1.8-2  ggplot2_2.2.0
>
>loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8      digest_0.6.10    psych_1.6.9      assertthat_0.1  
 [5] grid_3.3.0       plyr_1.8.4       gtable_0.2.0     magrittr_1.5    
 [9] scales_0.4.1     stringi_1.1.2    reshape2_1.4.2   lazyeval_0.2.0  
[13] labeling_0.3     tools_3.3.0      foreign_0.8-67   stringr_1.1.0   
[17] munsell_0.4.3    parallel_3.3.0   colorspace_1.3-1 mnormt_1.5-5    
[21] gridExtra_2.2.1  tibble_1.2  

I've been keeping all packages updated. Could it be related to ggplot2 version 2.2.0? (Just tried with 2.1.0 version and had the same issue)
[UPDATE: It really is related to ggplot2_2.2.0, works fine with 2.1.0.  One needs to uninstall 2.2.0, restart R and install 2.1.0]
Thanks,

**Comment by Rmadillo** [comment]
I have the same issue. I've been playing around in `likert.bar.plot` around lines 87 and 189 with various combinations of trying to reverse the data and the fill, e.g.,:

```
                geom_bar(data = results.high[nrow(results.high):1,], aes(fill = rev(variable)), 
                    stat = "identity")
```

I can get the colors to correctly order by using `rev` with the `fill` part, but the data is wrong, still in the wrong order from highest at 0 to lowest at the right end of the bar.

I did get the colors and order to work using this instead of the above:

```
                geom_bar(data = results.high, aes(fill = variable, group=rev(variable)), 
                    stat = "identity")
```

**However**, I don't know why it works, since the lines above them don't need the group formally specified. Hopefully the package owners will be able to sort that out?

**Comment by cgthigpen** [comment]
Likewise, I appreciate the excellent work to develop this package, but unfortunately I too am having the same issue. 

From the debugging by @Rmadillo it would seem to be a likert package issue, though I had initially thought it might be a ggplot2 problem. Any chance this will get addressed in the next package update?

**Comment by Rmadillo** [comment]
FWIW, the values/color order also fails to plot correctly when you use grouping and `centered = FALSE`.

**Comment by mansonp** [comment]
I also have new extra categories showing up on some grouped data plots.

**Comment by randallgrout** [comment]
I can second that this happens when using ggplot2 2.2.0.  Reverting to 2.1.0 fixes it.  Perhaps it is related to the new stacking methods used in the ggplot2.

**Comment by jpaulbrowning** [comment]
I have the same problem, and beat my head against the wall until finding this thread. ggplot2 2.1.0 fixed it for me as well.

**Comment by lisaerein** [comment]
I was having the same problem this fixed it - thank you so much for posting!!!!

**Comment by jbryer** [comment]
This has been fixed and on CRAN now.

**Comment by Rmadillo** [comment]
Thanks, Jason, for the update, but many more thanks for such a great package!!!

**Comment by avierse** [comment]
This still isn't working for me. Is there a package I should update? I tried re-ordering my levels and it's still not reading in the Likert plot.

Thanks!

**Comment by jbryer** [comment]
With all the changes to ggplot2, this package needs updating. It is on my
list to work on this summer.

**Comment by yrhe** [comment]
Hello, thank you very much for providing this very useful package! I noticed this issue has been closed, but I still have this issue, the color is incorrect.  The version of ggplot2 installed is 3.1.1.
